pull_request_rules:
  - name: Automatic merge when approved by Jimmy
    conditions:
      - "approved-reviews-by=rootsongjc"
      - "#approved-reviews-by>=2"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Automatic merge on approval by xuzhenwen
    conditions:
      - "approved-reviews-by=helight"
      - "#approved-reviews-by>=2"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Automatic merge when approved by majinghe
    conditions:
      - "approved-reviews-by=majinghe"
      - "#approved-reviews-by>=2"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Automatic merge when approved by liujinxin
    conditions:
      - "approved-reviews-by=scilla0531"
      - "#approved-reviews-by>=2"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Automatic merge when approved by zhanghaili
    conditions:
      - "approved-reviews-by=webup"
      - "#approved-reviews-by>=2"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Automatic merge when approved by zhangxiaohui
    conditions:
      - "approved-reviews-by=addozhang"
      - "#approved-reviews-by>=2"
      - base=zh
    actions:
      merge:
        method: merge
  - name: Ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it @{{author}}?
